// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package P1;

/************************************************************/
/**
 * 
 */
public class Alumne Matriculat
{
	/**
	 * 
	 */
	public String Nom;
	/**
	 * 
	 */
	public Qualificació qualificació;
};
