// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package P1;

/************************************************************/
/**
 * 
 */
public class Jugador {
	/**
	 * 
	 */
	public int numero;
	/**
	 * 
	 */
	public String localitat;
	/**
	 * 
	 */
	public String nom;
};
